name: apryt
description: A command-line tool for Flutter developers to manage production releases and versioning.
version: 1.1.0
repository: https://github.com/Rvkt/apryt-cli.git

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  yaml: ^3.1.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

executables:
  apryt: apryt